esphome:
  name: votronic-camper
  platform: ESP32
  board: nodemcu-32s

# Verweise auf deine lokale Komponente
external_components:
  - source:
      type: local
      path: ./components
    components:
      - votronic

wifi:
  ssid: "Dein WLAN-Name"
  password: "Dein WLAN-Passwort"

ota:
api:

# Binde deine Paketdatei ein, die deine Sensoren konfiguriert
packages:
  !include packages/votronic_device.yaml
